base:
  outputs:
    dev:
      type: duckdb
  target: dev
traffic_crashes_dbt:
  outputs:
    dev:
      type: bigquery
      dataset: dbt_transformations
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('path_to_keyfile') }}"
      location: us-central1
      method: service-account
      priority: interactive
      project: "{{ env_var('TF_VAR_project_id') }}"
      threads: 4
  target: dev
